### ISSUE TITLE
pivot_cache with float32 data does not stop

### ISSUE THREAD

**Issue by ghost** [ahwillia/NonNegLeastSquares.jl#31] opened 2021-04-18 05:15 UTC
Hello, I ran the following code [Julia v1.6.0, NonNegLeastSquares v0.3.0]:

```julia
using NonNegLeastSquares

A = [ -0.24  -0.82   1.35   0.36   0.35
      -0.53  -0.20  -0.76   0.98  -0.54
       0.22   1.25  -1.60  -1.37  -1.94
      -0.51  -0.56  -0.08   0.96   0.46
       0.48  -2.25   0.38   0.06  -1.29 ];

b = [-1.6,  0.19,  0.17,  0.31, -1.27];

A = Float32.(A);

b = Float32.(b);

x = NonNegLeastSquares.pivot_cache(A, b);
```
However, the execution did not stop. Do you have any ideas how to fix this? Thanks.

**Comment by JeffFessler** [comment] 2021-04-18 19:48
I can reproduce the issue you mention.
However, the following code worked fine, so my suggestion is to use the interface as documented in the README:

```julia
using NonNegLeastSquares

A = [ -0.24  -0.82   1.35   0.36   0.35
      -0.53  -0.20  -0.76   0.98  -0.54
       0.22   1.25  -1.60  -1.37  -1.94
      -0.51  -0.56  -0.08   0.96   0.46
       0.48  -2.25   0.38   0.06  -1.29 ]

b = [-1.6,  0.19,  0.17,  0.31, -1.27]

A32 = Float32.(A)
b32 = Float32.(b)

x64 = nonneg_lsq(A, b; alg=:pivot)
x32 = nonneg_lsq(A32, b32; alg=:pivot)
x32 ≈ x64
```

I'm going to close this issue for now, but feel free to reopen if you really need to access the non-exported function `pivot_cache` directly for some reason, but then please provide more explanation why you need to do it that way instead of using the documented API.

**Comment by ghost** [comment] 2021-04-18 20:23
Hello, @JeffFessler. I confirmed that this issue does not arise when `nonneg_lsq(A,b;alg=:pivot)`, but it sometimes arises when `nonneg_lsq(A,b;alg=:pivot,variant=:cache)`.

```julia
using Random, NonNegLeastSquares

Random.seed!(103);
A = rand(Float32, 100, 100);
b = rand(Float32, 100);
x32 = nonneg_lsq(A,b;alg=:pivot,variant=:cache);
```

**Comment by JeffFessler** [comment] 2021-04-19 02:24
I can confirm this issue.  The problem is that the default tolerance (1e-8) is too small for `Float32` types.
The workaround for now is this:

```julia
x = nonneg_lsq(A, b; alg=:pivot, variant=:cache, tol=1e-4)
```

I am working on a PR that will set the `tol` more appropriately based on the input data type, but that may take a while to get committed.

**Comment by JeffFessler** [comment] 2021-04-20 19:23
@tsano430
I just verified that the new tagged version 0.4.0 works fine with your MWE above, so I close this issue now.
BTW, you don't need semicolons at the line ends in Julia :)

**Closed as completed by JeffFessler** 2021-04-20 19:23 UTC
Labels: bug

**Comment by ghost** [comment] 2021-04-20 20:53
Thank you!
